### ISSUE TITLE
Cyber-City-Comics-App Checklist

### ISSUE THREAD

**Issue by yparmar123** [yparmar123/Cyber-City-Comics-App#1]
Requirements:

- [x] Use the xkcd API (see https://xkcd.com/json.html)
- [x] Has to be hosted on Heroku
- [x] Has to be done in Javascript without Jquery
- [x] Homepage displays the latest comic
- [x] Display 1 comic strip per page
- [x] Buttons to navigate to the previous and next comic strip
- [x] Display the date of when the comic strip was created
- [x] Ability to navigate to a specific comic strip by including the comic # in the URL
- [x] Parse transcript from API into a more readable format & display on the page
- [x] Make the page look nice using vanilla CSS (DO NOT use any CSS frameworks)

Bonus:
- [x] A random button that goes to a random comic strip
- [x] Make the site responsive
- [x] Each comic page has a counter that displays the amount of times this specific comic strip has been
viewed on your site

**Comment by yparmar123** [comment]
Project complete
